name: figma
description: A Figma API wrapper library for interacting with Figma documents, written in pure Dart.
version: 8.0.0-dev
homepage: https://github.com/arnemolland/figma
repository: https://github.com/arnemolland/figma
issue_tracker: https://github.com/arnemolland/figma/issues

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  collection: ^1.19.0
  copy_with_extension: ^9.0.0
  equatable: ^2.0.0
  http: ^1.0.0
  http2: ^2.0.0
  meta: any
  json_annotation: ^4.9.0

dev_dependencies:
  args: ^2.6.0
  build_runner: ^2.6.1
  change_case: ^2.2.0
  code_builder: ^4.10.1
  copy_with_extension_gen: ^9.1.1
  dart_style: ^3.1.1
  json_serializable: ^6.11.0
  lints: ^6.0.0
  markdown: ^7.3.0
  test: ^1.26.3
  yaml: ^3.1.3
